version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: taskhub-postgres-new
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: taskhub
      POSTGRES_MULTIPLE_DATABASES: taskhub_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    networks:
      - taskhub-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d taskhub"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  taskhub-network:
    driver: bridge
