version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test
      - DB_NAME=taskhub_test
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=postgres
      - DB_PORT=5432
      - JWT_SECRET=test-secret-key
    depends_on:
      postgres:
        condition: service_healthy
    command: npm test

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=taskhub_test
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d taskhub_test"]
      interval: 5s
      timeout: 5s
      retries: 5
