version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: taskhub-postgres-new
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: taskhub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskhub-network

volumes:
  postgres_data:

networks:
  taskhub-network:
