name: Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      - name: Build and test
        run: docker compose -f docker-compose.test.yml up --build --exit-code-from app

      - name: Clean up
        if: always()
        run: docker compose -f docker-compose.test.yml down
